#     COURSE: Linear algebra: theory and implementation
##    SECTION: Matrix rank

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math


---
# VIDEO: Computing rank: theory and practice
---


In [4]:
# make a matrix
m = 4
n = 6

# create a random matrix
A = np.random.randn(m,n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('rank = ' + str(ra))

# # set last column to be repeat of penultimate column
# B = A
# B[:,-1] = B[:,-2]
# print(B)

# set last row to be repeat of penultimate column
B = A
B[-1,:] = B[-2,:]
print(B)

rb = np.linalg.matrix_rank(B)
print('rank = ' + str(rb))

rank = 4
[[-1.18855987  1.03950767 -0.95407542  0.44021775 -0.20890917  0.49606906]
 [-0.48629294  0.30246798  0.06169722  0.48123894  0.93360843  1.26174243]
 [-0.19867198 -0.08470144  0.38041321  1.06531806 -0.69407146 -0.44530253]
 [-0.19867198 -0.08470144  0.38041321  1.06531806 -0.69407146 -0.44530253]]
rank = 3


In [5]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,-1] = A[:,-2]

# noise level
noiseamp = .0001

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))


rank (w/o noise) = 3
rank (with noise) = 4


# Code challenge: reduced-rank matrix via multiplication

In [22]:
# create a 10x10 matrix with rank=4 (use matrix multipliation)
A = np.random.randn(10,4)
B = np.random.randn(4,10)
C = A@B

print(np.shape(C))
print(np.linalg.matrix_rank(C))

(10, 10)
4


In [6]:
# generalize the procedure to create any MxN matrix with rank r
m = 50
n = 47
r = 5

A = np.random.randn(m,r) @ np.random.randn(r,n)
print(np.shape(A))
print(np.linalg.matrix_rank(A))

(50, 47)
5


# Code challenge: scalar multiplication and rank

In [44]:
# create two matrices: full-rank and a reduced-rank
m = 12
n = 6
r = 3

F = np.random.randn(m,n)
R = np.random.randn(m,r) @ np.random.randn(r,n)

print(np.linalg.matrix_rank(F))
print(np.linalg.matrix_rank(R))

6
3


In [45]:
# create some scaler
l = np.random.rand()*5
print(l)

1.4303020756853164


In [46]:
# print ranks of F, R, l*F, l*R
print(np.linalg.matrix_rank(F))
print(np.linalg.matrix_rank(R))

# scaler does not change the ranks of the matrices 
print(np.linalg.matrix_rank(l*F))
print(np.linalg.matrix_rank(l*R))

6
3
6
3


In [ ]:
# check whether rank(l*F)==;*rank(F)
## False because a rank must be an integer


---
# VIDEO: Rank of A^TA and AA^T
---


In [2]:
# matrix sizes
m = 14
n =  3

# create matrices
A = np.round( 10*np.random.randn(m,n) )

AtA = A.T@A
AAt = A@A.T

# get matrix sizes
sizeAtA = AtA.shape
sizeAAt = AAt.shape

# print info!
print('AtA: %dx%d, rank=%d' %(sizeAtA[0],sizeAtA[1],np.linalg.matrix_rank(AtA)))
print('AAt: %dx%d, rank=%d' %(sizeAAt[0],sizeAAt[1],np.linalg.matrix_rank(AAt)))

AtA: 3x3, rank=3
AAt: 14x14, rank=3


# Code challenge: rank of multiplied and summed matrices

In [11]:
# generate two matrices (A and B), 2x5
A = np.random.randn(2,5)
B = np.random.randn(2,5)

In [12]:
print(A), print()
print(B)

[[-0.59114432 -0.42717376 -0.61431399  0.39291897  0.00555613]
 [-0.06305334 -1.35018323 -0.70140993  0.4093386  -0.14867387]]

[[-0.12136491 -1.08253859  1.14915414 -0.45701363  1.40288701]
 [ 1.84189355 -0.46200863  0.30026578 -0.00213444 -0.62531071]]


In [13]:
# compute AtA and BtB
AtA = A.T@A
BtB = B.T@B

In [14]:
print(AtA),print()
print(BtB)

[[ 0.35342734  0.33765491  0.40737447 -0.25808198  0.00608991]
 [ 0.33765491  2.00547219  1.20945075 -0.72052678  0.19836353]
 [ 0.40737447  1.20945075  0.86935757 -0.52848978  0.10086812]
 [-0.25808198 -0.72052678 -0.52848978  0.3219434  -0.05867484]
 [ 0.00608991  0.19836353  0.10086812 -0.05867484  0.02213479]]

[[ 3.40730128 -0.71958851  0.41359062  0.051534   -1.32201702]
 [-0.71958851  1.38534177 -1.38272909  0.49572102 -1.22978039]
 [ 0.41359062 -1.38272909  1.41071479 -0.52582     1.42437402]
 [ 0.051534    0.49572102 -0.52582     0.20886601 -0.63980379]
 [-1.32201702 -1.22978039  1.42437402 -0.63980379  2.35910546]]


In [15]:
# find their ranks
print(np.linalg.matrix_rank(AtA))
print(np.linalg.matrix_rank(BtB))

2
2


In [21]:
# find ranks of AtA @ BtB
mul_mat = AtA@BtB
print(np.linalg.matrix_rank(mul_mat))
print(mul_mat.shape)

2
(5, 5)


In [17]:
# find ranks of AtA + BtB
sum_mat = AtA+BtB
print(np.linalg.matrix_rank(sum_mat))
print(sum_mat.shape)

4
(5, 5)



---
# VIDEO: Making a matrix full-rank by "shifting"
---


In [29]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round( 10*A.T@A )
# print(A),print()

# reduce the rank
A[:,0] = A[:,1]
A[:,2] = A[:,1]

# shift amount (l=lambda)
l = .00000001

# new matrix
B = A + l*np.eye(m,m)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))

rank(w/o shift) = 28
rank(with shift) = 30


# Code challenge: is this vector in the span of this set?

In [37]:
# determine whether this vestor
v = np.array([[1,2,3,4]]).T
print(v),print()

# in the span of these sets?
S = np.vstack(([4,3,6,2],[0,4,0,1])).T
T = np.vstack(([1,2,2,2],[0,0,1,2])).T
print(S),print()
print(T),print()

Sv = np.concatenate((S,v), axis=1)
Tv = np.concatenate((T,v), axis=1)
print(Sv),print()
print(Tv),print()

print()
print(np.linalg.matrix_rank(Sv)) # The rank is increased so it is not in the span
print(np.linalg.matrix_rank(Tv)) # The rank is not increased so it is in the same span

[[1]
 [2]
 [3]
 [4]]

[[4 0]
 [3 4]
 [6 0]
 [2 1]]

[[1 0]
 [2 0]
 [2 1]
 [2 2]]

[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]

[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]


3
2
